name: Enterprise DevSecops CICD Pipeline
on:
    push:
        branches:
            - dev
        paths:
            - client/**
            - server/**
            - .github/workflows/ci.yml
permissions:
    contents: write
    id-token: write       

jobs:
    gitleaks-scan:
        name: Gitleaks Scan name
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code from name
              uses: actions/Checkout@v4